####
# This can later be replaced with standard library...
from motion_CurrentConfig import *

class Locomotion:
    """BURST class Locomotion - generates and manages walking commands
    this class manages all the walking commands generated by upper behaviors"""

    def __init__ (self,ip,port):
        """ Constructor - creating motion proxy for a later use"""
        
        
    
