#!/bin/bash

HOST=192.168.7.110
MODULE=crossbuild/src/librecordermodule.so
if [ ! -e $MODULE ]; then
	echo you need to build the local version first
	exit -1
fi
if [ "$1" != "" ]; then
	HOST=$1
fi
echo copying to $HOST
scp $MODULE root@$HOST:/opt/naoqi/modules/lib

