import math

# Naoqi Constants

BALANCE_MODE_OFF = 0

# support modes
SUPPORT_MODE_LEFT, SUPPORT_MODE_DOUBLE_LEFT, SUPPORT_MODE_RIGHT, SUPPORT_MODE_DOUBLE_RIGHT = 0, 1, 2, 3

INTERPOLATION_LINEAR, INTERPOLATION_SMOOTH = 0, 1

# Math constants

DEG_TO_RAD = math.pi / 180.0

# Camera / Vision constants

IMAGE_WIDTH = 320.0
IMAGE_HEIGHT = 240.0

IMAGE_HALF_WIDTH = IMAGE_WIDTH / 2
IMAGE_HALF_HEIGHT = IMAGE_HEIGHT / 2
