#!/bin/sh

export LD_LIBRARY_PATH=$AL_DIR/extern/c/linux/lib/python2.5:$AL_DIR/extern/c/linux/lib:bin/
# just runs gdb and logs output
#gdb bin/nao_in_webots -ex run -ex bt -ex quit --quiet 2>&1 | cat > /tmp/nao_in_webots.gdb.log

# even better: runs gdb inside a screen, you can attach (poor mans remote debug)
# didn't work - couldn't find libController.so - I thought it would be in an
# environment varialbe (LD_PRELOAD) but either it doesn't pass on to SCREEN
# or something stranger is going on
#screen -S gdb gdb bin/nao_in_webots -ex run -ex bt

#strace -f bin/nao_in_webots 2>&1 | cat > /tmp/nao_in_webots.strace

# rich man's remote debugging
#gdbserver localhost:2333 bin/nao_in_webots

# just let it be
exec ./bin/nao_in_webots

