#
################################################################################
# Change according to module

TARGET_LIB=libburstmem.so

SRC=burstmem.cpp  burstmemmodule.cpp

################################################################################
# This part must be copied as is

ifdef ROOT
else
ROOT=../../
endif

include $(ROOT)/Makefile.local

# See this for details
include $(ROOT)/src/Makefile.base

